import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css"; //sice globals .css is inside (app_not_a_route) then again inside (homepage_not_a_route) thats why two time "../" . "../" this indicates a folder
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* this is session provider which we have wrapped in layout.tsx file  so that we can usesession in pages where next-auth is required*/}
      
      <body className={inter.className}> {children} <Toaster />  </body>
          
    </html>
  );
}
